export const cliAdapterFixtures = {
  argv: ["init", "--id", "athena", "--name", "Athena"],
  requirementCreateArgv: [
    "requirement",
    "create",
    "--id",
    "FUN-001",
    "--kind",
    "functional",
    "--title",
    "Persist metadata",
    "--subject",
    "Athena",
    "--level",
    "must",
    "--requirement",
    "persist project metadata",
    "--priority",
    "high",
    "--feature",
    "PERSISTENCE",
  ],
  requirementUpdateArgv: [
    "requirement",
    "update",
    "FUN-001",
    "--id",
    "FUN-001",
    "--kind",
    "functional",
    "--title",
    "Persist metadata updated",
    "--subject",
    "Athena",
    "--level",
    "must",
    "--requirement",
    "persist project metadata safely",
    "--priority",
    "high",
    "--feature",
    "PERSISTENCE",
  ],
  project: {
    id: "athena",
    name: "Athena",
  },
} as const;
